using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ShapePooling : MonoBehaviour
{
    public MyGrid myGrid;
    public List<Shape> shapePrefabs;
    int _currentShapeId = 0;
    // Start is called before the first frame update
    void Start()
    {
        // Invoke("GenerateRandomShape", .5f);
        GenerateRandomShape();
    }

    // Update is called once per frame
    void Update()
    {

    }

    public void GenerateRandomShape(){
        shapePrefabs[_currentShapeId].gameObject.SetActive(false);
        _currentShapeId = Random.Range(0, shapePrefabs.Count);
        shapePrefabs[_currentShapeId].gameObject.SetActive(true);
        if(myGrid.IsGameOver(shapePrefabs[_currentShapeId].dirID)){
            SingleplayerManager.instance.ShowGameOverScreen();
        }
    }

    public void FinishDroppingAboveShape(bool isValidDrop){
        //above shape, which is randomly generated by GenerateRandomShape()
        shapePrefabs[_currentShapeId].ResetPosition();
        shapePrefabs[_currentShapeId].gameObject.SetActive(!isValidDrop);
    }
}
