using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ShapePooling : MonoBehaviour
{
    public List<GameObject> shapePrefabs;
    int _currentShapeId = 0;
    // Start is called before the first frame update
    void Start()
    {
        // Invoke("GenerateRandomShape", .5f);
        GenerateRandomShape();
    }

    // Update is called once per frame
    void Update()
    {

    }

    public void GenerateRandomShape(){
        shapePrefabs[_currentShapeId].SetActive(false);
        _currentShapeId = Random.Range(0, shapePrefabs.Count);
        shapePrefabs[_currentShapeId].SetActive(true);
    }

    public void FinishDroppingAboveShape(bool isValidDrop){
        //above shape, which is randomly generated by GenerateRandomShape()
        shapePrefabs[_currentShapeId].GetComponent<Shape>().ResetPosition();
        shapePrefabs[_currentShapeId].SetActive(!isValidDrop);
    }
}
